// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnalvu5yaFHfITk7lxT7fVSKpTuNP4c_c',
    appId: '1:463091616448:web:32204b426ec7c49d817b25',
    messagingSenderId: '463091616448',
    projectId: 'fir-tutorial-4edd5',
    authDomain: 'fir-tutorial-4edd5.firebaseapp.com',
    storageBucket: 'fir-tutorial-4edd5.appspot.com',
    measurementId: 'G-Y6F5KM68KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3QxGi_XpEzIfUv5AWpLFqODwi_yg3Au0',
    appId: '1:463091616448:android:36c467e3922dbc17817b25',
    messagingSenderId: '463091616448',
    projectId: 'fir-tutorial-4edd5',
    storageBucket: 'fir-tutorial-4edd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmW11y2_F8mzUAAZCRoEFsSHHlgLv6sEI',
    appId: '1:463091616448:ios:aa77324e28c1d70e817b25',
    messagingSenderId: '463091616448',
    projectId: 'fir-tutorial-4edd5',
    storageBucket: 'fir-tutorial-4edd5.appspot.com',
    iosBundleId: 'com.example.firebaseTutorials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmW11y2_F8mzUAAZCRoEFsSHHlgLv6sEI',
    appId: '1:463091616448:ios:323812329cee5ce8817b25',
    messagingSenderId: '463091616448',
    projectId: 'fir-tutorial-4edd5',
    storageBucket: 'fir-tutorial-4edd5.appspot.com',
    iosBundleId: 'com.example.firebaseTutorials.RunnerTests',
  );
}
